### ISSUE TITLE
Request sample dataset

### ISSUE THREAD

**Issue by lamhoangtung** [mhashas/Document-Image-Unwarping-pytorch#1]
Thanks for the great work.

Can you provide us a toy sample dataset that have a couples of samples so we can have a better understanding of how to construct the training dataset ?

**Comment by raduslmn** [comment]
I also support this request, if you have a few examples that would be awesome. Also training data set folder structure.

**Comment by mhashas** [comment]
If you send me a couple of input images, I can try to create small toy dataset for you.

**Comment by lamhoangtung** [comment]
@mhashas Here you go
[toy_dataset.zip](https://github.com/mhashas/Document-Image-Unwarping-pytorch/files/4810011/toy_dataset.zip)

I'm glad that you could help  ^^. Thanks

**Comment by mhashas** [comment]
@lamhoangtung the idea is to provide me with flat images, and I warp them for you and give you the original images, deformed images, deformation field and inverted deformation field

**Comment by lamhoangtung** [comment]
@mhashas Here you go again. Many thanks for your help ^^

[toy_dataset_2.zip](https://github.com/mhashas/Document-Image-Unwarping-pytorch/files/4814560/toy_dataset_2.zip)

**Comment by mhashas** [comment]
Hi, thanks for the wait. Here you can download an example. I already structured it into test/train and created the appropriate folders. 

https://drive.google.com/file/d/16Ay3NVzFmsVe1saMOZam-9nHBE0xcmyA/view?usp=sharing
