### ISSUE TITLE
how to predict the test_pictures? There is  some wrong with 'python playground.py'

### ISSUE THREAD

**Issue by Williamwsk** [mhashas/Document-Image-Unwarping-pytorch#2]

**Comment by mhashas** [comment]
I need you to be a bit more specific. Have you trained your model on a dataset? If so, how does the dataset look like?

**Comment by mhashas** [comment]
Feel free to use this toy example dataset: https://drive.google.com/file/d/16Ay3NVzFmsVe1saMOZam-9nHBE0xcmyA/view?usp=sharing
